----- Output from ./tests/cgitest/raamattu.py -----
Traceback (most recent call last):
  File "/home/omartela/hive-projects/WebServer/./tests/cgitest/raamattu.py", line 128, in <module>
    send_chunked_genesis(GENESIS_TEXT)
  File "/home/omartela/hive-projects/WebServer/./tests/cgitest/raamattu.py", line 104, in send_chunked_genesis
    conn.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
----- End of output for ./tests/cgitest/raamattu.py -----
